import type { Metadata } from "next";
import "./globals.css";
import React, { Suspense } from "react";

import localFont from "next/font/local";
import NextTopLoader from "nextjs-toploader";
import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";

import { Lily_Script_One } from "next/font/google";

const lily = Lily_Script_One({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-gothic",
});

const yekan = localFont({
  src: [
    {
      path: "./ui/fonts/yekan/yekan-thin.ttf",
      weight: "100",
    },
    {
      path: "./ui/fonts/yekan/yekan-light.ttf",
      weight: "200",
    },
    {
      path: "./ui/fonts/yekan/yekan-medium.ttf",
      weight: "300",
    },
    {
      path: "./ui/fonts/yekan/yekan.ttf",
      weight: "400",
    },
    {
      path: "./ui/fonts/yekan/yekan-bold.ttf",
      weight: "600",
    },
    {
      path: "./ui/fonts/yekan/yekan-extrabold.ttf",
      weight: "900",
    },
  ],
  variable: "--font-yekan",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${yekan.variable} ${lily.variable} font-sans`}>
        <Suspense>
          <NextTopLoader color="#3EABAF" />
          <MantineProvider>{children}</MantineProvider>
        </Suspense>
      </body>
    </html>
  );
}
